[build]
  command = "npm run build"
  publish = "dist/client"
  functions = "netlify/functions"

[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200

[[redirects]]
  from = "/images/*"
  to = "/images/:splat"
  status = 200

[[redirects]]
  from = "/favicon.*"
  to = "/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/render"
  status = 200
  force = true

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["react-dom/server"]
  included_files = ["dist/**/*"]

[build.environment]
  NODE_VERSION = "20" 