[build]
  command = "npm run build"
  publish = "dist/client"
  functions = "dist/server"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "20" 