[build]
  command = "npm run build"
  publish = "dist/client"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/render"
  status = 200
  force = true

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["react-dom/server"]
  included_files = ["dist/client/**"]

[build.environment]
  NODE_VERSION = "20" 