[build]
  command = "npm run build"
  publish = "dist/client"
  functions = "dist/server"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/render"
  status = 200

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["react-dom/server"]

[build.environment]
  NODE_VERSION = "20" 